name: MysticCore
version: '${project.version}'
main: me.thomaszoord.mysticcube.Core
author: thomaszoord
api-version: '1.20'
depend: [Citizens]
commands:
  admin:
    description: Principal command for server admin setup
  spawn:
    description: Go to the spawn.
  mine:
    description: Go to the mine.
